# Generated by Django 3.1.13 on 2021-11-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_name', models.CharField(max_length=50)),
                ('projekt_nummer', models.IntegerField()),
                ('projekt_beschreibung', models.TextField()),
            ],
        ),
    ]
