# Generated by Django 3.1.13 on 2021-11-17 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_name', models.CharField(max_length=50)),
                ('projekt_nummer', models.IntegerField()),
                ('projekt_beschreibung', models.TextField(blank=True, null=True)),
                ('projekt_added', models.DateTimeField(auto_now_add=True)),
                ('projekt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjektArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projektart', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjektBranche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projektbranche', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjektDienstleistung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projektdienstleistung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjektNutzung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projektnutzung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjektPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projektphase', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjektSpezifikationen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_raumnutzung', models.CharField(max_length=50)),
                ('projekt_raumflaeche', models.IntegerField()),
                ('projekt_raumhoehe', models.IntegerField()),
                ('projekt_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.projekt')),
            ],
        ),
        migrations.AddField(
            model_name='projekt',
            name='projekt_art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projektart'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='projekt_branche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projektbranche'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='projekt_dienstleistung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projektdienstleistung'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='projekt_ersteller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projekt',
            name='projekt_nutzung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projektnutzung'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='projekt_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projektphase'),
        ),
    ]
