# Generated by Django 3.1.13 on 2021-11-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projektdienstleistung',
            name='projektdienstleistung',
            field=models.CharField(choices=[('Buero', 'Buero'), ('Test', 'Test'), ('Test2', 'Test2')], max_length=50),
        ),
    ]
