# Generated by Django 3.1.13 on 2021-11-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0003_auto_20211117_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projektart',
            name='projektart',
            field=models.CharField(choices=[('Neubau', 'Neubau'), ('Umbau', 'Umbau'), ('Sanierung', 'Sanierung'), ('Beratung', 'Beratung')], default='Vorprojekt', max_length=50),
        ),
        migrations.AlterField(
            model_name='projektdienstleistung',
            name='projektdienstleistung',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projektphase',
            name='projektphase',
            field=models.CharField(choices=[('Strategische Planung', 'Strategische Planung'), ('Vorstudie', 'Vorstudie'), ('Vorprojekt', 'Vorprojekt'), ('Bauprojekt', 'Bauprojekt'), ('Ausschreibung', 'Ausschreibung'), ('Realisierung', 'Realisierung'), ('Bewirtschaftung', 'Bewirtschaftung')], default='Vorprojekt', max_length=50),
        ),
    ]
