# Generated by Django 3.1.13 on 2021-11-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0004_auto_20211117_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abgabesystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abgabesystem', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Erzeugungstyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erzeugungstyp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gebaudenutzung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gebaudenutzung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gewerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gewerk', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Raumnutzung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raumnutzung', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kostenstammdaten_HLKS_Erzeugung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erzeugungstyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.erzeugungstyp')),
                ('gewerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.gewerk')),
            ],
        ),
        migrations.CreateModel(
            name='Kostenstammdaten_HLKS_Abgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abgabesystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.abgabesystem')),
                ('gebaudenutzung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.gebaudenutzung')),
                ('gewerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.gewerk')),
                ('raumnutzung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.raumnutzung')),
            ],
        ),
        migrations.CreateModel(
            name='Kostenstammdaten_Elektro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('einheitspreis_pro_m2', models.FloatField()),
                ('gebaudenutzung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.gebaudenutzung')),
                ('gewerk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.gewerk')),
                ('raumnutzung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.raumnutzung')),
            ],
        ),
        migrations.AlterField(
            model_name='projektspezifikationen',
            name='projekt_raumnutzung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.raumnutzung'),
        ),
    ]
