# Generated by Django 3.1.13 on 2021-11-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0005_auto_20211117_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projektspezifikationen',
            name='projekt_raumhoehe',
            field=models.FloatField(),
        ),
    ]
