# Generated by Django 3.1.13 on 2021-11-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0007_auto_20211117_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gewerk2',
            old_name='gewerk',
            new_name='gewerk2',
        ),
    ]
