# Generated by Django 3.1.13 on 2021-11-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0010_stammdaten_technickzentralen_elektro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
