# Generated by Django 3.1.13 on 2021-11-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0011_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projektspezifikationen',
            name='projekt_raumnutzung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.raumnutzung'),
        ),
    ]
