# Generated by Django 3.1.13 on 2021-11-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0012_auto_20211118_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kostenstammdaten_elektro',
            name='gewerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.gewerk'),
        ),
        migrations.AlterField(
            model_name='kostenstammdaten_elektro',
            name='raumnutzung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.raumnutzung'),
        ),
    ]
