# Generated by Django 3.1.13 on 2021-11-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vorstudie', '0016_auto_20211118_1151'),
        ('projekt', '0014_auto_20211118_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abgabesystem',
        ),
    ]
