# Generated by Django 3.1.13 on 2021-11-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0017_auto_20211118_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='umwandlung',
            name='gewerk2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.gewerk2'),
        ),
    ]
