# Generated by Django 3.1.13 on 2021-11-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0018_umwandlung_gewerk2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kostenstammdaten_hlks_erzeugung',
            name='einheitspreis_pro_m3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kostenstammdaten_hlks_erzeugung',
            name='gewerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.gewerk'),
        ),
        migrations.AlterField(
            model_name='kostenstammdaten_hlks_erzeugung',
            name='umwandlung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.umwandlung'),
        ),
    ]
