# Generated by Django 3.1.13 on 2021-11-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0019_auto_20211118_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technikzentralstammdaten_hlks',
            name='erzeugungstyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.erzeugungstyp'),
        ),
        migrations.AlterField(
            model_name='technikzentralstammdaten_hlks',
            name='gewerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.gewerk'),
        ),
        migrations.AlterField(
            model_name='technikzentralstammdaten_hlks',
            name='leistung_Pro_Gewerk_Therm_bis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technikzentralstammdaten_hlks',
            name='leistung_Pro_Gewerk_Therm_von',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technikzentralstammdaten_hlks',
            name='luftmenge_bis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technikzentralstammdaten_hlks',
            name='luftmenge_von',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technikzentralstammdaten_hlks',
            name='umwandlung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.umwandlung'),
        ),
        migrations.AlterField(
            model_name='technikzentralstammdaten_hlks',
            name='zentralengroesse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technikzentralstammdaten_hlks',
            name='zentralentyp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
