# Generated by Django 3.1.13 on 2021-11-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vorstudie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projekt')),
            ],
        ),
    ]
