# Generated by Django 3.1.13 on 2021-11-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0007_auto_20211117_1342'),
        ('vorstudie', '0003_auto_20211117_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technikflächen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt_spez', models.IntegerField()),
                ('erzeugungstyp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.erzeugungstyp')),
                ('gewerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.gewerk')),
            ],
        ),
        migrations.CreateModel(
            name='Leistung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leistung_pro_m2_Klassifizierung_Gewerk2', models.FloatField()),
                ('luftwechsel_pro_Person_Klassifizierung', models.FloatField()),
                ('flaeche_pro_Personenanzahl_Klassifizierung', models.FloatField()),
                ('raumtemparatur_Klassifizierung', models.FloatField()),
                ('gewerk2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.gewerk2')),
                ('klassifizierung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.klassifizierung')),
                ('projekt_spez', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projektspezifikationen')),
            ],
        ),
    ]
