# Generated by Django 3.1.13 on 2021-11-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorstudie', '0005_auto_20211117_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='technikflächen',
            name='name',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
    ]
