# Generated by Django 3.1.13 on 2021-11-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0007_auto_20211117_1342'),
        ('vorstudie', '0007_auto_20211117_1353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technikflächen',
            new_name='Technikflaechen',
        ),
    ]
