# Generated by Django 3.1.13 on 2021-11-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0007_auto_20211117_1342'),
        ('vorstudie', '0008_auto_20211117_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technikflaechen',
            old_name='projekt_name',
            new_name='projekt',
        ),
        migrations.RemoveField(
            model_name='leistung',
            name='projekt_spez',
        ),
        migrations.AddField(
            model_name='leistung',
            name='projekt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projekt'),
        ),
    ]
