# Generated by Django 3.1.13 on 2021-11-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vorstudie', '0010_auto_20211117_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technikflaechen',
            name='name_technik',
        ),
    ]
