# Generated by Django 3.1.13 on 2021-11-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0010_stammdaten_technickzentralen_elektro'),
        ('vorstudie', '0013_auto_20211117_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leistung',
            name='flaeche_pro_Personenanzahl_Klassifizierung',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leistung',
            name='gewerk2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.gewerk2'),
        ),
        migrations.AlterField(
            model_name='leistung',
            name='klassifizierung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.klassifizierung'),
        ),
        migrations.AlterField(
            model_name='leistung',
            name='leistung_pro_m2_Klassifizierung_Gewerk2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leistung',
            name='luftwechsel_pro_Person_Klassifizierung',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leistung',
            name='raumtemparatur_Klassifizierung',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
