# Generated by Django 3.1.13 on 2021-11-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorstudie', '0014_auto_20211117_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='leistung',
            name='leistung_pro_gewerk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leistung',
            name='luftwechsel_pro_nutzung',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leistung',
            name='personenanzahl_pro_nutzung',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
