# Generated by Django 3.1.13 on 2021-11-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0014_auto_20211118_1151'),
        ('vorstudie', '0015_auto_20211118_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gewerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.gewerk')),
                ('klassifizierung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.klassifizierung')),
                ('projekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Investitionskosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flaeche', models.IntegerField()),
                ('einheitspreis_pro_m2', models.IntegerField()),
                ('einheitspreis_pro_kw', models.IntegerField()),
                ('abgabesystem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.abgabesystem_hlks')),
                ('erzeugungstyp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.erzeugungstyp')),
                ('gewerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.gewerk')),
                ('leistung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vorstudie.leistung')),
                ('projekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Nutzungskosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projekt')),
            ],
        ),
        migrations.AlterField(
            model_name='technikflaechen',
            name='stammdaten_technikzentrale_elektro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.stammdaten_technickzentralen_elektro'),
        ),
        migrations.AlterField(
            model_name='technikflaechen',
            name='stammdaten_technikzentrale_hlks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.technikzentralstammdaten_hlks'),
        ),
        migrations.DeleteModel(
            name='Input_Investitionskosten',
        ),
    ]
