# Generated by Django 3.1.13 on 2021-11-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0015_delete_abgabesystem'),
        ('vorstudie', '0016_auto_20211118_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technikflaechen',
            name='stammdaten_technikzentrale_elektro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.stammdaten_technickzentralen_elektro'),
        ),
        migrations.AlterField(
            model_name='technikflaechen',
            name='stammdaten_technikzentrale_hlks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.technikzentralstammdaten_hlks'),
        ),
    ]
