# Generated by Django 3.1.13 on 2021-11-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0019_auto_20211118_1657'),
        ('vorstudie', '0017_auto_20211118_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technikflaechen',
            old_name='leistung_pro_gewerk',
            new_name='leistung_Pro_Gewerk',
        ),
        migrations.RenameField(
            model_name='technikflaechen',
            old_name='luftwechsel',
            new_name='luftwechsel_Pro_Nutzung',
        ),
        migrations.RemoveField(
            model_name='investitionskosten',
            name='abgabesystem',
        ),
        migrations.RemoveField(
            model_name='investitionskosten',
            name='einheitspreis_pro_kw',
        ),
        migrations.RemoveField(
            model_name='investitionskosten',
            name='einheitspreis_pro_m2',
        ),
        migrations.RemoveField(
            model_name='investitionskosten',
            name='erzeugungstyp',
        ),
        migrations.RemoveField(
            model_name='leistung',
            name='raumtemparatur_Klassifizierung',
        ),
        migrations.RemoveField(
            model_name='technikflaechen',
            name='erzeugungstyp',
        ),
        migrations.RemoveField(
            model_name='technikflaechen',
            name='stammdaten_technikzentrale_elektro',
        ),
        migrations.RemoveField(
            model_name='technikflaechen',
            name='stammdaten_technikzentrale_hlks',
        ),
        migrations.RemoveField(
            model_name='technikflaechen',
            name='zentralengroessen',
        ),
        migrations.RemoveField(
            model_name='technikflaechen',
            name='zentralentyp',
        ),
        migrations.AddField(
            model_name='investitionskosten',
            name='investitionskosten_Kw_Gewerk_Erzeugung',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='investitionskosten',
            name='investitionskosten_Kw_Gewerk_Erzeugung2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='investitionskosten',
            name='investitionskosten_m2_gewerk',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='investitionskosten',
            name='stammdateb_kosten_elektro',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='investitionskosten',
            name='stammdaten_kosten_hlks_abgabe',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='investitionskosten',
            name='stammdaten_kosten_hlks_erzeugung',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='investitionskosten',
            name='umwandlung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.umwandlung'),
        ),
        migrations.AddField(
            model_name='nutzungskosten',
            name='energieerzeuger',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutzungskosten',
            name='energiekosten_Pro_Gewerk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutzungskosten',
            name='energietraeger_Pro_Energietraeger',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutzungskosten',
            name='gewerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.gewerk'),
        ),
        migrations.AddField(
            model_name='nutzungskosten',
            name='investitionskosten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vorstudie.investitionskosten'),
        ),
        migrations.AddField(
            model_name='nutzungskosten',
            name='unterhaltsfaktor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutzungskosten',
            name='unterhaltskosten_Pro_Gewerk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technikflaechen',
            name='stammdaten_Technikzentrale_Elektro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.stammdaten_technickzentralen_elektro'),
        ),
        migrations.AddField(
            model_name='technikflaechen',
            name='stammdaten_Technikzentrale_Hlks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.technikzentralstammdaten_hlks'),
        ),
        migrations.AddField(
            model_name='technikflaechen',
            name='umwandlung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.umwandlung'),
        ),
        migrations.AlterField(
            model_name='investitionskosten',
            name='flaeche',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nutzungskosten',
            name='projekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projekt'),
        ),
        migrations.CreateModel(
            name='Leistung_variabl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variabler_Luftwechsel', models.FloatField(null=True)),
                ('raumtemparatur_sommer', models.FloatField(null=True)),
                ('raumtemparatur_winter', models.FloatField(null=True)),
                ('beleuchtungsstaerke', models.FloatField(null=True)),
                ('leistung_Pro_Gewerk2_Lueftung', models.FloatField(null=True)),
                ('leistung_Pro_Gewerk2_Beleuchtung', models.FloatField(null=True)),
                ('leistung_Pro_Gewerk_Heizung', models.FloatField(null=True)),
                ('leistung_Pro_Gewerk_Kaelte', models.FloatField(null=True)),
                ('leistung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vorstudie.leistung')),
                ('stammdaten_sia2024', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.nutzungsstammdaten_sia2024')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projekt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Energie_Variabl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energie', models.FloatField(null=True)),
                ('variabler_Luftwechsel', models.FloatField(null=True)),
                ('raumtemparatur_sommer', models.FloatField(null=True)),
                ('raumtemparatur_winter', models.FloatField(null=True)),
                ('beleuchtungsstaerke', models.FloatField(null=True)),
                ('Energie_pro_Gewerk2_Lüftung', models.FloatField(null=True)),
                ('Energie_pro_Gewerk2_Beleuchtung', models.FloatField(null=True)),
                ('Energie_pro_Gewerk_Heizung', models.FloatField(null=True)),
                ('Energie_pro_Gewerk_Kälte', models.FloatField(null=True)),
                ('stammdaten_sia2024', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.nutzungsstammdaten_sia2024')),
            ],
        ),
    ]
