# Generated by Django 3.1.13 on 2021-11-18 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0020_auto_20211118_1902'),
        ('vorstudie', '0018_auto_20211118_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energie_variabl',
            old_name='Energie_pro_Gewerk2_Beleuchtung',
            new_name='energie_pro_Gewerk2_Beleuchtung',
        ),
        migrations.RenameField(
            model_name='energie_variabl',
            old_name='Energie_pro_Gewerk2_Lüftung',
            new_name='energie_pro_Gewerk2_Lüftung',
        ),
        migrations.RenameField(
            model_name='energie_variabl',
            old_name='Energie_pro_Gewerk_Heizung',
            new_name='energie_pro_Gewerk_Heizung',
        ),
        migrations.RenameField(
            model_name='energie_variabl',
            old_name='Energie_pro_Gewerk_Kälte',
            new_name='energie_pro_Gewerk_Kälte',
        ),
        migrations.RemoveField(
            model_name='energie',
            name='gewerk',
        ),
        migrations.AddField(
            model_name='energie',
            name='gewerk2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.gewerk2'),
        ),
        migrations.AddField(
            model_name='energie',
            name='stammdaten_sia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.nutzungsstammdaten_sia2024'),
        ),
        migrations.AddField(
            model_name='energie',
            name='umwandlung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.umwandlung'),
        ),
        migrations.AddField(
            model_name='energie_variabl',
            name='treibhausemissionen_pro_gewerk_beleuchtung',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energie_variabl',
            name='treibhausemissionen_pro_gewerk_heizung',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energie_variabl',
            name='treibhausemissionen_pro_gewerk_kaelte',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energie_variabl',
            name='treibhausemissionen_pro_gewerk_lueftung',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='energie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vorstudie.energie'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='leistung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vorstudie.leistung'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='technikanteil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='technikflaeche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vorstudie.technikflaechen'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='projekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projekt'),
        ),
    ]
