# Generated by Django 3.1.13 on 2021-11-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorstudie', '0020_auto_20211118_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='investitionskosten',
            name='anzeigename',
            field=models.CharField(default='Investitionskosten', max_length=50),
        ),
    ]
