# Generated by Django 3.1.13 on 2021-11-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorstudie', '0021_investitionskosten_anzeigename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investitionskosten',
            name='anzeigename',
            field=models.CharField(max_length=50),
        ),
    ]
