# Generated by Django 3.1.13 on 2021-11-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorstudie', '0022_auto_20211118_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investitionskosten',
            name='anzeigename',
            field=models.CharField(default='invest', max_length=50),
        ),
    ]
