# Generated by Django 3.1.13 on 2021-11-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vorstudie', '0024_auto_20211118_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investitionskosten',
            old_name='investitionskosten_m2_elektro',
            new_name='investitionskosten_m2_gewerk',
        ),
        migrations.RemoveField(
            model_name='investitionskosten',
            name='investitionskosten_m2_heizung',
        ),
        migrations.RemoveField(
            model_name='investitionskosten',
            name='investitionskosten_m2_kaelte',
        ),
        migrations.RemoveField(
            model_name='investitionskosten',
            name='investitionskosten_m2_lueftung',
        ),
    ]
