# Generated by Django 3.1.13 on 2021-11-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0022_projektspezifikationen_projekt_gebauedenutzung'),
        ('vorstudie', '0027_remove_investitionskosten_investitionskosten_kw_gewerk_erzeugung2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technikflaechen',
            name='gewerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.gewerk'),
        ),
        migrations.AlterField(
            model_name='technikflaechen',
            name='leistung_Pro_Gewerk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technikflaechen',
            name='luftwechsel_Pro_Nutzung',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technikflaechen',
            name='projekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.projekt'),
        ),
        migrations.AlterField(
            model_name='technikflaechen',
            name='stammdaten_Technikzentrale_Elektro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.stammdaten_technickzentralen_elektro'),
        ),
        migrations.AlterField(
            model_name='technikflaechen',
            name='stammdaten_Technikzentrale_Hlks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.technikzentralstammdaten_hlks'),
        ),
        migrations.AlterField(
            model_name='technikflaechen',
            name='umwandlung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.umwandlung'),
        ),
    ]
